var _yt_www={};(function(m){var window=this;var pa,qa;m.aa=function(a){return function(){return m.ba[a].apply(this,arguments)}};m.ca=function(a){return void 0!==a};m.l=function(a,b,c){a=a.split(".");c=c||m.da;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&m.ca(b)?c[d]=b:c[d]?c=c[d]:c=c[d]={}};m.n=function(a,b){for(var c=a.split("."),d=b||m.da,e;e=c.shift();)if(null!=d[e])d=d[e];else return null;return d};m.ea=function(){};m.fa=function(a){a.getInstance=function(){return a.hb?a.hb:a.hb=new a}};
m.ga=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};m.ha=function(a){return"array"==m.ga(a)};m.ia=function(a){var b=m.ga(a);return"array"==b||"object"==b&&"number"==typeof a.length};m.ja=function(a){return"string"==typeof a};m.ka=function(a){return"number"==typeof a};m.la=function(a){return"function"==m.ga(a)};m.na=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};m.oa=function(a){return a[pa]||(a[pa]=++qa)};
var ra=function(a,b,c){return a.call.apply(a.bind,arguments)};var sa=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};m.q=function(a,b,c){m.q=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ra:sa;return m.q.apply(null,arguments)};
m.r=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};m.t=function(a,b){function c(){}c.prototype=b.prototype;a.K=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.base=function(a,c,f){for(var h=Array(arguments.length-2),k=2;k<arguments.length;k++)h[k-2]=arguments[k];return b.prototype[c].apply(a,h)}};m.ta=function(a){m.ta[" "](a);return a};
m.ua=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,m.ua);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};m.va=function(a){return(0,window.encodeURIComponent)(String(a))};
m.wa=function(a){if(!xa.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(ya,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(za,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(Aa,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(Ba,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(Ca,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(Da,"&#0;"));return a};
m.Ea=function(a,b){for(var c=0,d=(0,m.Fa)(String(a)).split("."),e=(0,m.Fa)(String(b)).split("."),f=Math.max(d.length,e.length),h=0;0==c&&h<f;h++){var k=d[h]||"",p=e[h]||"",w=RegExp("(\\d*)(\\D*)","g"),B=RegExp("(\\d*)(\\D*)","g");do{var P=w.exec(k)||["","",""],Y=B.exec(p)||["","",""];if(0==P[0].length&&0==Y[0].length)break;c=Ga(0==P[1].length?0:(0,window.parseInt)(P[1],10),0==Y[1].length?0:(0,window.parseInt)(Y[1],10))||Ga(0==P[2].length,0==Y[2].length)||Ga(P[2],Y[2])}while(0==c)}return c};
var Ga=function(a,b){return a<b?-1:a>b?1:0};m.Ha=function(a){return String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()})};m.Ia=function(a){var b=m.ja(void 0)?"undefined".replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"):"\\s";return a.replace(new RegExp("(^"+(b?"|["+b+"]+":"")+")([a-z])","g"),function(a,b,e){return b+e.toUpperCase()})};m.Ja=function(a,b,c){b=m.Ka(a,b,c);return 0>b?null:m.ja(a)?a.charAt(b):a[b]};
m.Ka=function(a,b,c){for(var d=a.length,e=m.ja(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return f;return-1};m.Ma=function(a,b){return 0<=(0,m.Na)(a,b)};m.Oa=function(a,b){var c=(0,m.Na)(a,b),d;(d=0<=c)&&m.Pa(a,c);return d};m.Pa=function(a,b){m.Qa.splice.call(a,b,1)};m.Ra=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};m.u=function(){this.kb=this.kb;this.va=this.va};m.Sa=function(a,b){m.Ta(a,m.r(m.Ua,b))};
m.Ta=function(a,b){a.va||(a.va=[]);a.va.push(m.ca(void 0)?(0,m.q)(b,void 0):b)};m.Ua=function(a){a&&"function"==typeof a.dispose&&a.dispose()};m.Va=function(){m.u.call(this);this.wa=[];this.Nb={}};m.Wa=function(a){Xa(m.Ya,arguments)};m.v=function(a,b){return a in m.Ya?m.Ya[a]:b};m.x=function(a,b){m.la(a)&&(a=m.Za(a));return window.setTimeout(a,b)};m.$a=function(a,b){m.la(a)&&(a=m.Za(a));return window.setInterval(a,b)};m.ab=function(a){window.clearTimeout(a)};m.bb=function(a){window.clearInterval(a)};
m.Za=function(a){return a&&window.yterr?function(){try{return a.apply(this,arguments)}catch(b){throw m.cb(b),b;}}:a};m.cb=function(a,b){var c=m.n("yt.www.errors.log");c?c(a,b):(c=m.v("ERRORS")||[],c.push([a,b]),m.Wa("ERRORS",c))};m.db=function(a){return a in m.eb};m.fb=function(a,b,c){var d=b||{};if(a=a in m.eb?m.eb[a]:c)for(var e in d)a=a.replace(new RegExp("\\$"+e,"gi"),function(){return d[e]});return a};var Xa=function(a,b){if(1<b.length){var c=b[0];a[c]=b[1]}else{var d=b[0];for(c in d)a[c]=d[c]}};
m.y=function(a,b,c){var d=gb();if(d){var e=d.subscribe(a,function(){if(!m.hb||m.hb!=e){var d=arguments,h=function(){ib[e]&&b.apply(c||window,d)};try{jb[a]?h():m.x(h,0)}catch(k){m.cb(k)}}},c);ib[e]=!0;kb[a]||(kb[a]=[]);kb[a].push(e);return e}return 0};m.lb=function(a){var b=gb();b&&("number"==typeof a?a=[a]:"string"==typeof a&&(a=[(0,window.parseInt)(a,10)]),(0,m.z)(a,function(a){b.unsubscribeByKey(a);delete ib[a]}))};m.A=function(a,b){var c=gb();return c?c.publish.apply(c,arguments):!1};
m.mb=function(a,b){jb[a]=!0;var c=gb(),c=c?c.publish.apply(c,arguments):!1;jb[a]=!1;return c};var gb=function(){return m.n("yt.pubsub.instance_")};m.nb=function(a){if(a.classList)return a.classList;a=a.className;return m.ja(a)&&a.match(/\S+/g)||[]};m.C=function(a,b){return a.classList?a.classList.contains(b):m.Ma(m.nb(a),b)};m.D=function(a,b){a.classList?a.classList.add(b):m.C(a,b)||(a.className+=0<a.className.length?" "+b:b)};
m.E=function(a,b){a.classList?a.classList.remove(b):m.C(a,b)&&(a.className=(0,m.ob)(m.nb(a),function(a){return a!=b}).join(" "))};m.pb=function(a,b,c){c?m.D(a,b):m.E(a,b)};m.qb=function(a,b,c){return Math.min(Math.max(a,b),c)};m.rb=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};m.sb=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};m.tb=function(a,b,c){for(var d in a)if(b.call(c,a[d],d,a))return d};m.ub=function(a,b){b in a&&delete a[b]};
m.vb=function(a,b,c){if(b in a)throw Error('The object already contains the key "'+b+'"');a[b]=c};m.wb=function(a){var b={},c;for(c in a)b[c]=a[c];return b};m.xb=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<yb.length;f++)c=yb[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};m.zb=function(a){var b=arguments.length;if(1==b&&m.ha(arguments[0]))return m.zb.apply(null,arguments[0]);for(var c={},d=0;d<b;d++)c[arguments[d]]=!0;return c};
var Ab=function(a){return-1!=m.Bb.indexOf(a)};var Cb=function(){var a=m.da.document;return a?a.documentMode:void 0};m.Db=function(a){return Eb[a]||(Eb[a]=0<=m.Ea(Fb,a))};m.Gb=function(a){return m.F&&m.Hb>=a};m.G=function(a){return m.ja(a)?window.document.getElementById(a):a};m.Ib=function(a){return m.Jb(window.document,a)};m.Jb=function(a,b){return m.ja(b)?a.getElementById(b):b};
m.H=function(a,b){var c=b||window.document,d=null;c.querySelectorAll&&c.querySelector?d=c.querySelector("."+a):d=m.Kb("*",a,b)[0];return d||null};
m.Kb=function(a,b,c){var d=window.document;c=c||d;a=a&&"*"!=a?a.toUpperCase():"";if(c.querySelectorAll&&c.querySelector&&(a||b))return c.querySelectorAll(a+(b?"."+b:""));if(b&&c.getElementsByClassName){c=c.getElementsByClassName(b);if(a){for(var d={},e=0,f=0,h;h=c[f];f++)a==h.nodeName&&(d[e++]=h);d.length=e;return d}return c}c=c.getElementsByTagName(a||"*");if(b){d={};for(f=e=0;h=c[f];f++)a=h.className,"function"==typeof a.split&&m.Ma(a.split(/\s+/),b)&&(d[e++]=h);d.length=e;return d}return c};
m.Lb=function(a,b){m.rb(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:d in Mb?a.setAttribute(Mb[d],b):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,b):a[d]=b})};m.Nb=function(a,b,c){return m.Ob(window.document,arguments)};
m.Ob=function(a,b){var c=b[0],d=b[1];if(!Pb&&d&&(d.name||d.type)){c=["<",c];d.name&&c.push(' name="',m.wa(d.name),'"');if(d.type){c.push(' type="',m.wa(d.type),'"');var e={};m.xb(e,d);delete e.type;d=e}c.push(">");c=c.join("")}c=a.createElement(c);d&&(m.ja(d)?c.className=d:m.ha(d)?c.className=d.join(" "):m.Lb(c,d));2<b.length&&m.Qb(a,c,b,2);return c};
m.Qb=function(a,b,c,d){function e(c){c&&b.appendChild(m.ja(c)?a.createTextNode(c):c)}for(;d<c.length;d++){var f=c[d];!m.ia(f)||m.na(f)&&0<f.nodeType?e(f):(0,m.z)(Rb(f)?m.Ra(f):f,e)}};m.Sb=function(a){for(var b;b=a.firstChild;)a.removeChild(b)};var Tb=function(a){if(!a)return null;if(a.firstChild)return a.firstChild;for(;a&&!a.nextSibling;)a=a.parentNode;return a?a.nextSibling:null};
var Ub=function(a){if(!a)return null;if(!a.previousSibling)return a.parentNode;for(a=a.previousSibling;a&&a.lastChild;)a=a.lastChild;return a};m.Vb=function(a){return 9==a.nodeType?a:a.ownerDocument||a.document};var Rb=function(a){if(a&&"number"==typeof a.length){if(m.na(a))return"function"==typeof a.item||"string"==typeof a.item;if(m.la(a))return"function"==typeof a.item}return!1};m.Xb=function(a,b,c,d){c||(a=a.parentNode);c=null==d;for(var e=0;a&&(c||e<=d);){if(b(a))return a;a=a.parentNode;e++}return null};
m.Yb=function(a){return function(){return a}};m.Zb=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}};m.$b=function(){};m.ac=function(a){if(a instanceof m.$b)return a;if("function"==typeof a.fb)return a.fb(!1);if(m.ia(a)){var b=0,c=new m.$b;c.next=function(){for(;;){if(b>=a.length)throw m.bc;if(b in a)return a[b++];b++}};return c}throw Error("Not implemented");};
m.cc=function(a,b,c){if(m.ia(a))try{(0,m.z)(a,b,c)}catch(d){if(d!==m.bc)throw d;}else{a=m.ac(a);try{for(;;)b.call(c,a.next(),void 0,a)}catch(e){if(e!==m.bc)throw e;}}};m.dc=function(a){if(m.ia(a))return m.Ra(a);a=m.ac(a);var b=[];m.cc(a,function(a){b.push(a)});return b};m.ec=function(a,b,c,d,e,f,h){var k="";a&&(k+=a+":");c&&(k+="//",b&&(k+=b+"@"),k+=c,d&&(k+=":"+d));e&&(k+=e);f&&(k+="?"+f);h&&(k+="#"+h);return k};
m.fc=function(a){if(gc){gc=!1;var b=m.da.location;if(b){var c=b.href;if(c&&(c=m.hc(c))&&c!=b.hostname)throw gc=!0,Error();}}return a.match(ic)};m.jc=function(a){return a?(0,window.decodeURI)(a):a};m.hc=function(a){return m.jc(m.fc(a)[3]||null)};m.kc=function(a){a=m.fc(a);return m.ec(null,null,null,null,a[5],a[6],a[7])};m.lc=function(a){if(a[1]){var b=a[0],c=b.indexOf("#");0<=c&&(a.push(b.substr(c)),a[0]=b=b.substr(0,c));c=b.indexOf("?");0>c?a[1]="?":c==b.length-1&&(a[1]=void 0)}return a.join("")};
m.mc=function(a,b,c){if(m.ha(b))for(var d=0;d<b.length;d++)m.mc(a,String(b[d]),c);else null!=b&&c.push("&",a,""===b?"":"=",m.va(b))};var nc=function(a,b){for(var c in b)m.mc(c,b[c],a);return a};m.oc=function(a){a=nc([],a);a[0]="";return a.join("")};m.pc=function(a,b){return m.lc(nc([a],b))};m.qc=function(a,b,c){a&&(c?a&&(a=m.Nb("iframe",{src:'javascript:"data:text/html,<body><img src=\\"'+a+'\\"></body>"',style:"display:none"}),m.Vb(a).body.appendChild(a)):rc(a,b))};
var rc=function(a,b){var c=new window.Image,d=""+sc++;tc[d]=c;c.onload=c.onerror=function(){b&&tc[d]&&b();delete tc[d]};c.src=a;c=eval("null")};m.uc=function(a,b,c){vc(c)[a]=b||(0,m.I)();b||wc(a)};var xc=function(a,b){yc(void 0).yt_sts=a;m.uc("_start",b,void 0)};var zc=function(a){return Math.round(Ac.timing.navigationStart+a)};
var Bc=function(a){var b=window.location.protocol,c=Ac.getEntriesByType("resource"),d=c.filter(function(a){return 0==a.name.indexOf(b+"//fonts.googleapis.com/css?family=")})[0],c=c.filter(function(a){return 0==a.name.indexOf(b+"//fonts.gstatic.com/s/")}).reduce(function(a,b){return b.duration>a.duration?b:a},{duration:0});d&&0<d.startTime&&0<d.responseEnd&&(a.wfcs=zc(d.startTime),a.wfce=zc(d.responseEnd));c&&0<c.startTime&&0<c.responseEnd&&(a.wffs=zc(c.startTime),a.wffe=zc(c.responseEnd))};
var Cc=function(a){var b=vc(a),c=Dc(a).span,d=yc(a),e=m.n("yt.timing.reportbuilder_");if(e){if(e=e(b,c,d,a))Ec(e),Fc(a),Gc();return window.NaN}e={v:2,s:"youtube",action:m.v("TIMING_ACTION")};if(Ac.now&&Ac.timing){var f=Ac.timing.navigationStart+Ac.now(),f=Math.round((0,m.I)()-f);d.yt_hrd=f}var f=m.v("TIMING_INFO")||{},h;for(h in f)d[h]=f[h];h=d.srt;delete d.srt;var k;h||0===h||(k=Ac.timing||{},h=Math.max(0,k.responseStart-k.navigationStart),(0,window.isNaN)(h)&&d.pt&&(h=d.pt));if(h||0===h)d.srt=h;
d.h5jse&&(f=window.location.protocol+m.n("ytplayer.config.assets.js"),(f=Ac.getEntriesByName?Ac.getEntriesByName(f)[0]:null)?d.h5jse=Math.round(d.h5jse-f.responseEnd):delete d.h5jse);b.aft||(b.aft=b.pbr&&b.pbs>b.pbr?b.pbr:b.pbs?b.pbs:b.vr?b.vr:b.ol);f=b._start;if(!Hc){k||(k=Ac.timing||{});var p;t:if(p=k,p.msFirstPaint)p=Math.max(0,p.msFirstPaint);else{var w=window.chrome;if(w&&(w=w.loadTimes,m.la(w))){var w=w(),B=1E3*Math.min(w.requestTime||window.Infinity,w.startLoadTime||window.Infinity),B=window.Infinity===
B?0:p.navigationStart-B;p=Math.max(0,Math.round(1E3*w.firstPaintTime+B)||0);break t}p=0}0<p&&p>f&&(b.fpt=p);p=k.redirectEnd-k.redirectStart;0<p&&(c.rtime_=p);p=k.domainLookupEnd-k.domainLookupStart;0<p&&(c.dns_=p);p=k.connectEnd-k.connectStart;0<p&&(c.tcp_=p);p=k.connectEnd-k.secureConnectionStart;k.secureConnectionStart&&0<p&&(c.stcp_=p);p=k.responseStart-k.requestStart;0<p&&(c.req_=p);p=k.responseEnd-k.responseStart;0<p&&(c.rcv_=p);m.v("EXP_WEBFONT_ENABLED")&&Ac.getEntriesByType&&Bc(b);Hc=!0}for(var P in d)"_"!=
P.charAt(0)&&(e[P]=d[P]);d={};P=[];for(var Y in b)"_"!=Y.charAt(0)&&(p=Math.max(Math.round(b[Y]-f),0),d[Y]=p,P.push(Y+"."+p));e.rt=P.join(",");b={};Y=[];for(var ma in c)"_"!=ma.charAt(0)&&(b[ma]=c[ma],Y.push(ma+"."+c[ma]));e.it=Y.join(",");(c=m.n("ytdebug.logTiming"))&&c(e,d,b);Fc(a);Gc();m.v("EXP_DEFER_CSI_PING")?(Ic(),Jc=e,Kc=m.x(Ic,0)):Ec(e);return d.aft+(h||0)};
var Lc=function(a,b){var c=m.v("TIMING_ACTION"),d=vc(b);if(c&&d._start)if(c=m.v("TIMING_WAIT",[]),!a&&c.length){for(var e=!0,f=0,h=c.length;f<h;++f)if(!(c[f]in d)){e=!1;break}if(e)return Cc(b)}else if(d.ol||d.aft)return Cc(b);return window.NaN};var Mc=function(a){if(m.v("TIMING_WAIT"))a=Lc(!1,a);else t:{var b=m.v("TIMING_ACTION"),c=!!m.v("TIMING_WFF"),d=vc(a);if(b&&d._start){if(c&&d.vr||!c&&(d.ol||d.aft)){a=Cc(a);break t}a&&Cc(a)}a=window.NaN}return a};
var Ec=function(a){m.v("EXP_DEFER_CSI_PING")&&(m.ab(Kc),Jc=null);var b="https:"==window.location.protocol?"https://gg.google.com/csi":"http://csi.gstatic.com/csi",c="",d;for(d in a)c+="&"+d+"="+a[d];m.qc(b+"?"+c.substring(1))};var Ic=function(a){Jc&&(a&&(Jc.yt_fss=a),Ec(Jc))};var vc=function(a){return Dc(a).tick};var yc=function(a){return Dc(a).info};var Dc=function(a){return m.n("ytcsi."+(a||"")+"data_")||Fc(a)};
var Fc=function(a){var b={tick:{},span:{},info:{}};m.l("ytcsi."+(a||"")+"data_",b,void 0);return b};m.Nc=function(){return!!m.n("yt.scheduler.instance")};m.Oc=function(){return m.Nc()&&m.C(window.document.body,"exp-js-scheduler-more")};m.Pc=function(a,b){void 0===b&&(b=window.NaN);var c=m.n("yt.scheduler.instance.addJob");return c?((0,window.isNaN)(b)&&(b=0),c(a,0,b)):(0,window.isNaN)(b)?(a(),window.NaN):m.x(a,b||0)};m.Qc=function(a,b){return m.Pc(a,b)};
m.Rc=function(a){var b=m.n("yt.scheduler.instance.cancelJob");b?b(a):m.ab(a)};m.Sc=function(a){for(var b=0,c=a.length;b<c;b++)m.Rc(a[b])};m.Tc=function(a,b,c,d,e){this.name=a;this.deps=b||[];this.page=c||"";this.B=d?m.Za(d):null;this.A=e?m.Za(e):null;this.wa=[];this.j=this.k=0};m.Uc=function(a){m.Oc()?(m.Rc(a.k),a.k=m.Qc((0,m.q)(a.init,a))):a.init()};
m.Vc=function(a){a.name in Wc&&Xc(a.name);Wc[a.name]={reqs:[],disable:(0,m.q)(a.disable,a)};(0,m.z)(a.deps,function(b){if(!(b in Wc))throw Error("Module "+b+" required by "+a.name);Wc[b].reqs.push(a.name)});a.enable()};var Xc=function(a){if(a in Wc){var b=Wc[a];(0,m.z)(b.reqs,function(a){Xc(a)});try{b.disable()}catch(c){}delete Wc[a]}};m.Yc=function(a){return a&&"readyState"in a?a.readyState:0};
var Zc=function(){if(m.v("SCHEDULE_AJAX")&&window.XMLHttpRequest&&!$c){ad=m.v("SCHEDULER_BUFFER_LENGTH");var a=window.XMLHttpRequest;bd=a.prototype.abort;cd=a.prototype.open;$c=a.prototype.send;a.prototype.abort=dd;a.prototype.open=ed;a.prototype.send=fd}};var dd=function(){gd(!0);bd.call(this)};var ed=function(){this.url=arguments[1];cd.apply(this,arguments)};
var fd=function(){var a=this,b=arguments;if(a.url&&a.url.match(hd))$c.apply(a,b);else{if("onloadend"in a)a.addEventListener("loadend",function(){4==m.Yc(a)&&gd(!0)},!1);else{var c=a.onreadystatechange;a.onreadystatechange=function(){4==m.Yc(a)&&gd(!0);c&&c.apply(this,arguments)}}id.push(function(){$c.apply(a,b)});gd()}};var gd=function(a){a&&(jd=!1,m.ab(kd));if(!jd&&id.length)if(ad&&!ld())m.ab(md),md=m.x(gd,100);else{jd=!0;a=id.shift();try{a()}catch(b){gd(!0)}kd=m.x(m.r(gd,!0),5E3)}};
var ld=function(){var a=ad,b=m.n("yt.player.getPlayerByElement");if(!b)return!0;var b=b("player-api"),c=m.v("ADS_DATA");return b&&(!c||!c.show_instream)&&b.getVideoLoadedFraction&&b.getDuration&&b.getCurrentTime&&b.getPlayerState?(c=b.getVideoLoadedFraction()*b.getDuration()-b.getCurrentTime(),0>=b.getPlayerState()||c>a||.3<b.getVideoLoadedFraction()):!0};m.J=function(a,b){return a?a.dataset?a.dataset[m.nd(b)]:a.getAttribute("data-"+b):null};
m.od=function(a,b){return a?a.dataset?m.nd(b)in a.dataset:a.hasAttribute?!!a.hasAttribute("data-"+b):!!a.getAttribute("data-"+b):!1};m.nd=function(a){return pd[a]||(pd[a]=String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()}))};m.qd=function(a,b){var c=m.rd(a);window.spf.script.load(a,c,b)};m.sd=function(a,b){var c=m.rd(a);window.spf.script.ignore(c,b)};m.td=function(a){a&&(m.ja(a)?m.qd(a):m.ha(a)?(0,m.z)(a,function(a){m.td(a)}):m.rb(a,function(a,c){m.qd(c,function(){m.td(a)})}))};
m.rd=function(a){var b="";if(a){var c=a.indexOf("jsbin/"),d=a.lastIndexOf(".js"),e=c+6;-1<c&&-1<d&&d>e&&(b=a.substring(e,d),b=b.replace(ud,""),b=b.replace(vd,""),b=b.replace("debug-",""),b=b.replace("tracing-",""))}return b};var wd=function(a){a=m.xd(a);return m.yd(a)||(null===a?!1:"google"==a[1]?!0:"google"==a[2]?"au"==a[0]&&"com"==a[1]?!0:"uk"==a[0]&&"co"==a[1]?!0:!1:!1)};m.yd=function(a){return null===a?!1:"com"==a[0]&&a[1].match(/^youtube(?:-nocookie)?$/)?!0:!1};
m.xd=function(a){a=(0,m.zd)(a);return null===a?null:a.split(".").reverse()};m.Ad=function(a,b){m.qc("/gen_204?"+a,b)};
var Bd=function(a){a=a||{};this.url=a.url||"";this.urlV8=a.url_v8||"";this.urlV9As2=a.url_v9as2||"";this.args=a.args||m.wb(Cd);this.assets=a.assets||{};this.attrs=a.attrs||m.wb(Dd);this.params=a.params||m.wb(Ed);this.minVersion=a.min_version||"8.0.0";this.fallback=a.fallback||null;this.fallbackMessage=a.fallbackMessage||null;this.html5=!!a.html5;this.disable=a.disable||{};this.loaded=!!a.loaded;this.messages=a.messages||{}};m.Fd=function(a){a instanceof Bd||(a=new Bd(a));return a};
var Gd=function(){return null!=m.Hd};m.Id=function(){return m.Hd?m.Hd.invoke():null};m.Jd=function(a){var b=a.cloneNode(!1);"TR"==b.tagName||"SELECT"==b.tagName?(0,m.z)(a.childNodes,function(a){b.appendChild(m.Jd(a))}):b.innerHTML=a.innerHTML;return b};
m.Kd=function(a){if(a=a||window.event){for(var b in a)b in Ld||(this[b]=a[b]);this.scale=a.scale;this.rotation=a.rotation;this.ua=a;(b=a.target||a.srcElement)&&3==b.nodeType&&(b=b.parentNode);this.target=b;if(b=a.relatedTarget)try{b=b.nodeName?b:null}catch(c){b=null}else"mouseover"==this.type?b=a.fromElement:"mouseout"==this.type&&(b=a.toElement);this.relatedTarget=b;this.clientX=void 0!=a.clientX?a.clientX:a.pageX;this.clientY=void 0!=a.clientY?a.clientY:a.pageY;this.keyCode=a.keyCode?a.keyCode:
a.which;this.charCode=a.charCode||("keypress"==this.type?this.keyCode:0);this.altKey=a.altKey;this.ctrlKey=a.ctrlKey;this.shiftKey=a.shiftKey;"MozMousePixelScroll"==this.type?(this.wheelDeltaX=a.axis==a.HORIZONTAL_AXIS?a.detail:0,this.wheelDeltaY=a.axis==a.HORIZONTAL_AXIS?0:a.detail):window.opera?(this.wheelDeltaX=0,this.wheelDeltaY=a.detail):0==a.wheelDelta%120?"WebkitTransform"in window.document.documentElement.style?window.chrome&&0==window.navigator.platform.indexOf("Mac")?(this.wheelDeltaX=a.wheelDeltaX/
-30,this.wheelDeltaY=a.wheelDeltaY/-30):(this.wheelDeltaX=a.wheelDeltaX/-1.2,this.wheelDeltaY=a.wheelDeltaY/-1.2):(this.wheelDeltaX=0,this.wheelDeltaY=a.wheelDelta/-1.6):(this.wheelDeltaX=a.wheelDeltaX/-3,this.wheelDeltaY=a.wheelDeltaY/-3);this.Bk=a.pageX;this.Ck=a.pageY}};m.Md=function(a,b,c,d){return m.tb(m.Nd,function(e){return e[0]==a&&e[1]==b&&e[2]==c&&e[4]==!!d})};
m.K=function(a,b,c,d){if(!a||!a.addEventListener&&!a.attachEvent)return"";d=!!d;var e=m.Md(a,b,c,d);if(e)return e;var e=++Od.count+"",f=!("mouseenter"!=b&&"mouseleave"!=b||!a.addEventListener||"onmouseenter"in window.document),h;h=f?function(d){d=new m.Kd(d);if(!m.Xb(d.relatedTarget,function(b){return b==a},!0))return d.currentTarget=a,d.type=b,c.call(a,d)}:function(b){b=new m.Kd(b);b.currentTarget=a;return c.call(a,b)};h=m.Za(h);m.Nd[e]=[a,b,c,h,d];a.addEventListener?"mouseenter"==b&&f?a.addEventListener("mouseover",
h,d):"mouseleave"==b&&f?a.addEventListener("mouseout",h,d):"mousewheel"==b&&"MozBoxSizing"in window.document.documentElement.style?a.addEventListener("MozMousePixelScroll",h,d):a.addEventListener(b,h,d):a.attachEvent("on"+b,h);return e};m.Pd=function(a){this.g=a};m.Qd=function(a){a=(a.g.cookie||"").split(m.Rd);for(var b=[],c=[],d,e,f=0;e=a[f];f++)d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:b,values:c}};
m.Sd=function(a,b,c){m.Td.set(""+a,b,c,"/","youtube.com")};m.Ud=function(a,b){return m.Td.get(""+a,b)};m.Vd=function(a,b){a=!!a;m.l("_lactCookie",a,window);if(null==m.n("_lact",window)){if(a&&b){var c=m.Ud("ACTIVITY","-1");m.l("_lact",(0,window.parseInt)(c,10),window)}else m.l("_lact",-1,window),Wd();m.K(window.document,"keypress",Wd);m.K(window.document,"mousedown",Wd);m.K(window.document,"mouseup",Wd)}};
var Wd=function(){var a=m.n("_lact",window);null==a&&(m.Vd(),a=m.n("_lact",window));var b=(0,m.I)();m.l("_lact",b,window);m.n("_lactCookie",window)&&1E3<=b-a&&m.Sd("ACTIVITY",""+b)};m.Xd=function(){var a=m.n("_lact",window);return null==a?-1:Math.max((0,m.I)()-a,0)};m.Yd=function(a,b,c){var d=m.hc(a);if(d==m.hc(window.location.href)||!d&&0==a.lastIndexOf("/",0))if(a=m.kc(a),d=a.indexOf("#"),a=0>d?a:a.substr(0,d))c?(c=(0,window.parseInt)(c,10),(0,window.isFinite)(c)&&0<c&&Zd(a,b,c)):Zd(a,b)};
var Zd=function(a,b,c){for(var d=0,e=0;e<a.length;++e)d=31*d+a.charCodeAt(e),d%=4294967296;a="s_tempdata-"+d;c=c||5;b=b?m.oc(b):"";m.Sd(a,b,c)};m.$d=function(a,b,c){c=c||"";window.location=m.pc(a,b||{})+c};m.ae=function(a,b){var c=window.ytspf||{};b&&m.Yd(a,b);c.enabled?window.spf.navigate(a):m.$d(a)};m.be=function(a,b,c){var d=m.v("EVENT_ID");d&&(b||(b={}),b.ei||(b.ei=d));b&&m.Yd(a,b);if(c)return!1;m.ae(a);return!0};var ce=function(a){m.da.setTimeout(function(){throw a;},0)};
var de=function(){var a=m.da.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&(a=function(){var a=window.document.createElement("iframe");a.style.display="none";a.src="";window.document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host,a=(0,m.q)(function(a){if(("*"==d||a.origin==
d)&&a.data==c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&!Ab("Trident")&&!Ab("MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(m.ca(c.next)){c=c.next;var a=c.Hp;c.Hp=null;a()}};return function(a){d.next={Hp:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof window.document&&"onreadystatechange"in window.document.createElement("script")?function(a){var b=
window.document.createElement("script");b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};window.document.documentElement.appendChild(b)}:function(a){m.da.setTimeout(a,0)}};var ee=function(a,b){fe||ge();he||(fe(),he=!0);ie.push(new je(a,b))};
var ge=function(){if(m.da.Promise&&m.da.Promise.resolve){var a=m.da.Promise.resolve();fe=function(){a.then(ke)}}else fe=function(){var a=ke;!m.la(m.da.setImmediate)||m.da.Window&&m.da.Window.prototype.setImmediate==m.da.setImmediate?(le||(le=de()),le(a)):m.da.setImmediate(a)}};var ke=function(){for(;ie.length;){var a=ie;ie=[];for(var b=0;b<a.length;b++){var c=a[b];try{c.re.call(c.scope)}catch(d){ce(d)}}}he=!1};var je=function(a,b){this.re=a;this.scope=b};
m.me=function(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0};m.ne=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};m.oe=function(a,b){this.j=0;this.C=void 0;this.g=this.k=null;this.A=this.B=!1;try{var c=this;a.call(b,function(a){pe(c,2,a)},function(a){pe(c,3,a)})}catch(d){pe(this,3,d)}};m.qe=function(a){return new m.oe(function(b){b(a)})};
var re=function(a,b){if(0==a.j)if(a.k){var c=a.k;if(c.g){for(var d=0,e=-1,f=0,h;h=c.g[f];f++)if(h=h.If)if(d++,h==a&&(e=f),0<=e&&1<d)break;0<=e&&(0==c.j&&1==d?re(c,b):(d=c.g.splice(e,1)[0],se(c,d,3,b)))}}else pe(a,3,b)};var te=function(a,b){a.g&&a.g.length||2!=a.j&&3!=a.j||ue(a);a.g||(a.g=[]);a.g.push(b)};
m.ve=function(a,b,c,d){var e={If:null,Gn:null,Hn:null};e.If=new m.oe(function(a,h){e.Gn=b?function(c){try{var e=b.call(d,c);a(e)}catch(w){h(w)}}:a;e.Hn=c?function(b){try{var e=c.call(d,b);!m.ca(e)&&b instanceof we?h(b):a(e)}catch(w){h(w)}}:h});e.If.k=a;te(a,e);return e.If};
var pe=function(a,b,c){if(0==a.j){if(a==c)b=3,c=new TypeError("Promise cannot resolve to itself");else{if(m.ne(c)){a.j=1;c.then(a.G,a.J,a);return}if(m.na(c))try{var d=c.then;if(m.la(d)){xe(a,c,d);return}}catch(e){b=3,c=e}}a.C=c;a.j=b;ue(a);3!=b||c instanceof we||ye(a,c)}};var xe=function(a,b,c){function d(b){f||(f=!0,a.J(b))}function e(b){f||(f=!0,a.G(b))}a.j=1;var f=!1;try{c.call(b,e,d)}catch(h){d(h)}};var ue=function(a){a.B||(a.B=!0,ee(a.H,a))};
var se=function(a,b,c,d){if(2==c)b.Gn(d);else{if(b.If)for(;a&&a.A;a=a.k)a.A=!1;b.Hn(d)}};var ye=function(a,b){a.A=!0;ee(function(){a.A&&ze.call(null,b)})};var we=function(a){m.ua.call(this,a)};var Ae=function(a){this.k=a;this.j=null;var b=this;a.then(function(a){b.j=a})};
var Be=function(a,b){var c=b||{},d=Ce().then(function(b){return b(a,{apiKey:c.of||c.apiKey,environment:c.pf||c.environment,helpCenterPath:c.lA||c.helpCenterPath,locale:c.locale||c.locale,productData:c.mA||c.productData,receiverUri:c.nA||c.receiverUri,theme:c.theme||c.theme,window:c.window||c.window})});return new Ae(d)};
var Ce=function(){if(De)return De;var a=m.n("help.service.Lazy.create");return a?De=m.qe(a):De=(new m.oe(function(a,c){var d=window.document.createElement("script");d.async=!0;d.src="https://www.gstatic.com/inproduct_help/service/lazy.min.js";d.onload=d.onreadystatechange=function(){d.readyState&&"loaded"!=d.readyState&&"complete"!=d.readyState||a(null)};d.onerror=c;(window.document.head||window.document.getElementsByTagName("head")[0]).appendChild(d)})).then(function(){var a=m.n("help.service.Lazy.create");
if(!a)throw Error("Failed to load help.service.Lazy.create from https://www.gstatic.com/inproduct_help/service/lazy.min.js");return a})};var Ee=function(a,b,c){a.k.then(function(a){a[b].apply(a,c)})};var Fe=function(a){a=a.match(/[\d]+/g);if(!a)return"";a.length=3;return a.join(".")};var Ge=function(a){return(a=a.exec(m.Bb))?a[1]:""};
var He=function(){this.k=this.j=this.g=0;this.A="";var a=m.n("window.navigator.plugins"),b=m.n("window.navigator.mimeTypes"),a=a&&a["Shockwave Flash"],b=b&&b["application/x-shockwave-flash"],b=a&&b&&b.enabledPlugin&&a.description||"";if(a=b){var c=a.indexOf("Shockwave Flash");0<=c&&(a=a.substr(c+15));for(var c=a.split(" "),d="",a="",e=0,f=c.length;e<f;e++)if(d)if(a)break;else a=c[e];else d=c[e];d=d.split(".");c=(0,window.parseInt)(d[0],10)||0;d=(0,window.parseInt)(d[1],10)||0;e=0;if("r"==a.charAt(0)||
"d"==a.charAt(0))e=(0,window.parseInt)(a.substr(1),10)||0;a=[c,d,e]}else a=[0,0,0];this.A=b;b=a;this.g=b[0];this.j=b[1];this.k=b[2];if(0>=this.g){var h,k,p,w;if(m.Ie)try{h=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(B){h=null}else p=window.document.body,w=window.document.createElement("object"),w.setAttribute("type","application/x-shockwave-flash"),h=p.appendChild(w);if(h&&"GetVariable"in h)try{k=h.GetVariable("$version")}catch(P){k=""}p&&w&&p.removeChild(w);(h=k||"")?(h=h.split(" ")[1].split(","),
h=[(0,window.parseInt)(h[0],10)||0,(0,window.parseInt)(h[1],10)||0,(0,window.parseInt)(h[2],10)||0]):h=[0,0,0];this.g=h[0];this.j=h[1];this.k=h[2]}};var Je=function(a,b,c,d){b="string"==typeof b?b.split("."):[b,c,d];b[0]=(0,window.parseInt)(b[0],10)||0;b[1]=(0,window.parseInt)(b[1],10)||0;b[2]=(0,window.parseInt)(b[2],10)||0;return a.g>b[0]||a.g==b[0]&&a.j>b[1]||a.g==b[0]&&a.j==b[1]&&a.k>=b[2]};
var Ke=function(a){return-1<a.A.indexOf("Gnash")&&-1==a.A.indexOf("AVM2")||9==a.g&&1==a.j||9==a.g&&0==a.j&&1==a.k?!1:9<=a.g};var Me=function(a){return m.Ne?!Je(a,11,2):m.Oe?!Je(a,11,3):!Ke(a)};m.Pe=function(){return m.Qe?"Webkit":m.Re?"Moz":m.F?"ms":m.Se?"O":null};m.Te=function(){return m.Qe?"-webkit":m.Re?"-moz":m.F?"-ms":m.Se?"-o":null};m.Ue=function(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d};
m.Ve=function(a,b){return a&&b?b instanceof m.Ue?b.left>=a.left&&b.right<=a.right&&b.top>=a.top&&b.bottom<=a.bottom:b.x>=a.left&&b.x<=a.right&&b.y>=a.top&&b.y<=a.bottom:!1};m.We=function(a,b){var c=m.Ha(b);if(void 0===a.style[c]){var d=m.Pe()+m.Ia(c);if(void 0!==a.style[d])return d}return c};m.Xe=function(a,b){"number"==typeof a&&(a=(b?Math.round(a):a)+"px");return a};m.Ye=function(a,b){a.style.display=b?"":"none"};m.Ze=function(){this.g="";this.j=$e};
var af=function(a){return a instanceof m.Ze&&a.constructor===m.Ze&&a.j===$e?a.g:"type_error:Const"};var bf=function(){this.g="";this.j=cf};var df=function(a){var b=new bf;b.g=a;return b};var ef=function(){this.g=ff};var gf=function(){this.g=hf};var jf=function(){this.g="";this.k=kf;this.j=null};m.lf=function(a){return a instanceof jf&&a.constructor===jf&&a.k===kf?a.g:"type_error:SafeHtml"};
m.mf=function(a,b){if(!nf.test(a))throw Error("Invalid tag name <"+a+">.");if(a.toLowerCase()in of)throw Error("Tag name <"+a+"> is not allowed for SafeHtml.");var c=null,d="<"+a;if(b)for(var e in b){if(!nf.test(e))throw Error('Invalid attribute name "'+e+'".');var f=b[e];if(null!=f){var h,k=a;h=e;if(f instanceof m.Ze)f=af(f);else if("style"==h.toLowerCase()){if(!m.na(f))throw Error('The "style" attribute requires goog.html.SafeStyle or map of style properties, '+typeof f+" given: "+f);if(!(f instanceof
bf)){var k="",p=void 0;for(p in f){if(!/^[-_a-zA-Z0-9]+$/.test(p))throw Error("Name allows only [-_a-zA-Z0-9], got: "+p);var w=f[p];null!=w&&(w instanceof m.Ze?w=af(w):pf.test(w)||(w="zClosurez"),k+=p+":"+w+";")}f=k?df(k):qf}k=void 0;k=f instanceof bf&&f.constructor===bf&&f.j===cf?f.g:"type_error:SafeStyle";f=k}else{if(/^on/i.test(h))throw Error('Attribute "'+h+'" requires goog.string.Const value, "'+f+'" given.');if(h.toLowerCase()in rf)if(f instanceof gf)f=f instanceof gf&&f.constructor===gf&&f.g===
hf?"":"type_error:TrustedResourceUrl";else if(f instanceof ef)f=f instanceof ef&&f.constructor===ef&&f.g===ff?"":"type_error:SafeUrl";else throw Error('Attribute "'+h+'" on tag "'+k+'" requires goog.html.SafeUrl or goog.string.Const value, "'+f+'" given.');}f.af&&(f=f.$e());h=h+'="'+m.wa(String(f))+'"';d=d+(" "+h)}}e=void 0;m.ca(e)?m.ha(e)||(e=[e]):e=[];!0===sf[a.toLowerCase()]?d+=">":(c=tf(e),d+=">"+m.lf(c)+"</"+a+">",c=c.ag());(e=b&&b.dir)&&(/^(ltr|rtl|auto)$/i.test(e)?c=0:c=null);return uf(d,c)};
var tf=function(a){function b(a){if(m.ha(a))(0,m.z)(a,b);else{if(!(a instanceof jf)){var f=null;a.Dk&&(f=a.ag());a=uf(m.wa(a.af?a.$e():String(a)),f)}d+=m.lf(a);a=a.ag();0==c?c=a:0!=a&&c!=a&&(c=null)}}var c=0,d="";(0,m.z)(arguments,b);return uf(d,c)};var uf=function(a,b){var c=new jf;c.g=a;c.j=b;return c};m.vf=function(a,b){(a=m.G(a))&&a.style&&(m.Ye(a,b),m.pb(a,"hid",!b))};m.L=function(a){(0,m.z)(arguments,function(a){m.vf(a,!0)})};
var wf=function(a,b){var c=m.v("FEEDBACK_LOCALE_LANGUAGE"),d=m.xf,e=m.v("FEEDBACK_LOCALE_EXTRAS",{});a?m.xb(d,a):m.xb(d,e);try{var f,h=m.n("yt.player.getPlayerByElement");(f=h?h("player-api"):null)&&f.pauseVideo&&f.pauseVideo();var k=He.getInstance();d.flashVersion=k.getVersion().join(".");f&&(d.playback_id=f.getVideoData().cpn)}catch(p){}b&&m.xb(d,{trackingParam:b});return{helpCenterPath:"/youtube",locale:c,productData:d}};
var yf=function(){var a=m.v("SESSION_INDEX"),b=m.v("FEEDBACK_BUCKET_ID"),c={abuseLink:"https://support.google.com/youtube/bin/answer.py?answer=140536",customZIndex:"2000000005"};a&&(c.authuser=a+"");b&&(c.bucket=b);return c};m.zf=function(a,b){try{var c=(a||"59")+"",d=wf(b),e=yf();Be(c,d).A(e);return!1}catch(f){return!0}};
m.Af=function(a,b,c,d,e,f,h,k){b=(b||"59")+"";d=wf(d,h);a={context:c,anchor:a,enableSendFeedback:f?!1:!0,defaultHelpArticleId:k};m.xb(a,yf());try{var p=Be(b,d);if(e&&!Bf)try{p.g(a),Bf=!0}catch(w){}p.B(a);return!1}catch(B){return!0}};m.Cf=function(a,b,c,d){return m.Af(void 0,d,b,c,void 0,void 0,void 0,a)};m.Df=function(){var a=m.Ud("PREF");if(a)for(var a=(0,window.unescape)(a).split("&"),b=0;b<a.length;b++){var c=a[b].split("="),d=c[0];(c=c[1])&&(m.Ef[d]=c.toString())}};
var Ff=function(a){if(/^f([1-9][0-9]*)$/.test(a))throw"ExpectedRegexMatch: "+a;};var Gf=function(a){if(!/^\w+$/.test(a))throw"ExpectedRegexMismatch: "+a;};m.Hf=function(a){a=void 0!==m.Ef[a]?m.Ef[a].toString():null;return null!=a&&/^[A-Fa-f0-9]+$/.test(a)?(0,window.parseInt)(a,16):null};m.If=function(a,b){return!!((m.Hf("f"+(Math.floor(b/31)+1))||0)&1<<b%31)};
var Jf=function(a,b,c){if(b){a=m.ja(a)?m.Ib(a):a;c=m.Fd(c);var d=m.wb(c.attrs);d.tabindex=0;var e=m.wb(c.params);e.flashvars=m.oc(c.args);if(m.Ie){d.classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000";e.movie=b;b=window.document.createElement("object");for(var f in d)b.setAttribute(f,d[f]);for(f in e)d=window.document.createElement("param"),d.setAttribute("name",f),d.setAttribute("value",e[f]),b.appendChild(d)}else{d.type="application/x-shockwave-flash";d.src=b;b=window.document.createElement("embed");
b.setAttribute("name",d.id);for(f in d)b.setAttribute(f,d[f]);for(f in e)b.setAttribute(f,e[f])}e=window.document.createElement("div");e.appendChild(b);a.innerHTML=e.innerHTML}};m.Kf=function(a,b){a=m.ja(a)?m.Ib(a):a;b=m.Fd(b);if(window!=window.top){var c=null;window.document.referrer&&(c=window.document.referrer.substring(0,128));b.args.framer=c}c=Lf();Je(c,b.minVersion)?(c=Mf(b,c),Jf(a,c,b)):Nf(a,b,c)};
var Of=function(a,b,c){if(a&&a.attrs&&a.attrs.id){a=m.Fd(a);var d=!!b,e=m.G(a.attrs.id),f=e?e.parentNode:null;if(e&&f){if(window!=window.top){var h=null;if(window.document.referrer){var k=window.document.referrer.substring(0,128);wd(k)||(h=k)}else h="unknown";h&&(d=!0,a.args.framer=h)}h=Lf();if(Je(h,a.minVersion)){var k=Mf(a,h),p="";-1<window.navigator.userAgent.indexOf("Sony/COM2")||(p=e.getAttribute("src")||e.movie);(p!=k||d)&&Jf(f,k,a);Me(h)&&Pf()}else Nf(f,a,h);c&&c()}else m.x(function(){Of(a,
b,c)},50)}};var Nf=function(a,b,c){0==c.g&&b.fallback?b.fallback():0==c.g&&b.fallbackMessage?b.fallbackMessage():a.innerHTML='<div id="flash-upgrade">'+m.fb("FLASH_UPGRADE",void 0,'You need to upgrade your Adobe Flash Player to watchthis video. <br> <a href="http://get.adobe.com/flashplayer/">Download it from Adobe.</a>')+"</div>"};var Mf=function(a,b){var c;(c=Ke(b)&&a.url)||(c=(-1<window.navigator.userAgent.indexOf("Sony/COM2")&&!Je(b,9,1,58)?!1:!0)&&a.urlV9As2);return c||a.urlV8||a.url};
var Lf=function(){var a=He.getInstance(),b=m.Df.getInstance();b.set("fv",a.getVersion().join("."));b.save();return a};var Pf=function(){var a=m.G("flash10-promo-div"),b=m.If(m.Df.getInstance(),107);a&&!b&&m.L(a)};m.Qf=function(a,b){var c=a.match(Rf);window.spf.style.load(a,c?c[1]:"",b)};
var Sf=function(){if(2.2==Tf)return!0;var a;a=m.n("yt.player.utils.videoElement_");a||(a=window.document.createElement("video"),m.l("yt.player.utils.videoElement_",a,void 0));try{return!(!a||!a.canPlayType||!a.canPlayType('video/mp4; codecs="avc1.42001E, mp4a.40.2"')&&!a.canPlayType('video/webm; codecs="vp8.0, vorbis"'))}catch(b){return!1}};var Uf=function(){};m.Vf=function(){};m.Wf=function(a){this.g=a};m.Xf=function(){var a=null;try{a=window.localStorage||null}catch(b){}this.g=a};
var Yf=function(){var a=null;try{a=window.sessionStorage||null}catch(b){}this.g=a};m.Zf=function(a){a=String(a);if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);};m.$f=function(a){return m.ag(new m.bg(void 0),a)};
m.bg=function(a){this.g=a};m.ag=function(a,b){var c=[];cg(a,b,c);return c.join("")};
var cg=function(a,b,c){switch(typeof b){case "string":dg(b,c);break;case "number":c.push((0,window.isFinite)(b)&&!(0,window.isNaN)(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(null==b){c.push("null");break}if(m.ha(b)){var d=b.length;c.push("[");for(var e="",f=0;f<d;f++)c.push(e),e=b[f],cg(a,a.g?a.g.call(b,String(f),e):e,c),e=",";c.push("]");break}c.push("{");d="";for(f in b)Object.prototype.hasOwnProperty.call(b,f)&&(e=b[f],"function"!=typeof e&&
(c.push(d),dg(f,c),c.push(":"),cg(a,a.g?a.g.call(b,f,e):e,c),d=","));c.push("}");break;case "function":break;default:throw Error("Unknown type: "+typeof b);}};var dg=function(a,b){b.push('"',a.replace(eg,function(a){if(a in fg)return fg[a];var b=a.charCodeAt(0),e="\\u";16>b?e+="000":256>b?e+="00":4096>b&&(e+="0");return fg[a]=e+b.toString(16)}),'"')};m.gg=function(a){this.g=a};var hg=function(a){this.g=a};var ig=function(a){this.data=a};var jg=function(a){return!m.ca(a)||a instanceof ig?a:new ig(a)};
var kg=function(a){this.g=a};m.lg=function(a){var b=a.creation;a=a.expiration;return!!a&&a<(0,m.I)()||!!b&&b>(0,m.I)()};m.mg=function(a){this.g=a};m.ng=function(a,b,c){var d=c&&0<c?c:0;c=d?(0,m.I)()+1E3*d:0;if((d=d?m.og:m.pg)&&window.JSON){m.ja(b)||(b=JSON.stringify(b,void 0));try{d.set(a,b,c)}catch(e){d.remove(a)}}};m.qg=function(a){if(!m.pg&&!m.og||!window.JSON)return null;var b;try{b=m.pg.get(a)}catch(c){}if(!m.ja(b))try{b=m.og.get(a)}catch(d){}if(!m.ja(b))return null;try{b=JSON.parse(b,void 0)}catch(e){}return b};
var rg=function(){var a={volume:100,muted:!1},b=m.qg("yt-player-volume")||{};a.volume=(0,window.isNaN)(b.volume)?100:m.qb(b.volume,0,100);a.muted=void 0==b.muted?!1:b.muted;return a};
var sg=function(a,b){m.u.call(this);this.k=this.vf=a;this.H=b;this.C=!1;this.g={};this.U=this.J=null;this.O=new m.Va;m.Sa(this,this.O);this.A={};this.B=this.X=this.j=this.Aa=this.da=null;this.N=!1;this.ga=this.G=null;this.$={};this.Fa=["onReady"];this.oa=null;this.za=0;this.T={};tg(this);this.ue("onVolumeChange",(0,m.q)(this.Sp,this));this.ue("onError",(0,m.q)(this.Rp,this));this.ue("onTabOrderChange",(0,m.q)(this.Qp,this));this.ue("WATCH_LATER_VIDEO_ADDED",(0,m.q)(this.Tp,this));this.ue("WATCH_LATER_VIDEO_REMOVED",
(0,m.q)(this.Vp,this))};
var ug=function(a,b){a.Aa=b;a.da=b.clone();a.j=a.da.attrs.id||a.j;"video-player"==a.j&&(a.j=a.H,a.da.attrs.id=a.H);a.k.id==a.j&&(a.j=a.j+"-player",a.da.attrs.id=a.j);var c=a.da.args,d;(d=a.da.args.eurl)||(d=(d=window.document.location.toString())&&-1!=d.search(vg)?window.document.referrer&&window.document.referrer.substring(0,128)||"unknown":d);c.eurl=d;a.da.args.enablejsapi="1";a.da.args.playerapiid=a.H;a.X||(a.X=wg(a,a.da.args.jsapicallback||"onYouTubePlayerReady"));a.da.args.jsapicallback=null;
if(c=a.da.attrs.width)a.k.style.width=m.Xe(Number(c)||c,!0);if(c=a.da.attrs.height)a.k.style.height=m.Xe(Number(c)||c,!0);a.k.style.overflow="hidden"};var yg=function(a){a.da.loaded||(a.da.loaded=!0,"0"!=a.da.args.autoplay?a.g.loadVideoByPlayerVars(a.da.args):a.g.cueVideoByPlayerVars(a.da.args))};var zg=function(a){if(!m.ca(a.da.disable.flash)){var b=a.da.disable,c;c=Je(Lf(),a.da.minVersion);b.flash=!c}return!a.da.disable.flash};
var Ag=function(a){var b=Bg(a);b&&b.stopVideo&&b.stopVideo();if(zg(a)){var c=a.da;b&&b.getUpdatedConfigurationData&&(b=m.Fd(b.getUpdatedConfigurationData()),b.args.video_id==c.args.video_id&&(c=b));c.args.autoplay=1;c.args.html5_unavailable="1";ug(a,c);Cg(a,"flash")}};
var Cg=function(a,b){if(!a.fa()){if(!b){var c;if(!(c=!a.da.html5&&zg(a))){if(!m.ca(a.da.disable.html5)){if(c=Sf())c=Dg(a)||a.da.assets.js;a.da.disable.html5=!c;c||(a.da.args.html5_unavailable="1")}c=!!a.da.disable.html5}b=c?zg(a)?"flash":"unsupported":"html5"}("flash"==b?a.Fy:"html5"==b?a.Gy:a.Hy).call(a)}};var Dg=function(a){var b=!0,c=Bg(a);c&&a.da&&(a=a.da,b=m.J(c,"version")==a.assets.js);return b&&!!m.n("yt.player.Application.create")};
var Bg=function(a){var b=m.G(a.j);!b&&a.k&&a.k.querySelector&&(b=a.k.querySelector("#"+a.j));return b};var Eg=function(a,b,c){var d=b[c];return function(){try{return a.oa=null,d.apply(b,arguments)}catch(e){"Bad NPObject as private data!"!=e.message&&(e.message+=" ("+c+")",a.oa=e,m.cb(e,"WARNING"))}}};
var tg=function(a){a.C=!1;if(a.U)for(var b in a.A)a.U(b,a.A[b]);for(var c in a.T)m.ab((0,window.parseInt)(c,10));a.T={};a.J=null;a.U=null;for(var d in a.g)a.g[d]=null;a.g.addEventListener=(0,m.q)(a.ue,a);a.g.removeEventListener=(0,m.q)(a.At,a);a.g.destroy=(0,m.q)(a.dispose,a);a.g.getLastError=(0,m.q)(a.xt,a);a.g.getPlayerType=(0,m.q)(a.zt,a);a.g.getCurrentVideoConfig=(0,m.q)(a.wt,a);a.g.loadNewVideoConfig=(0,m.q)(a.lj,a);a.g.isReady=(0,m.q)(a.Bt,a)};
var wg=function(a,b){var c=b;if("string"==typeof b){if(a.$[b])return a.$[b];c=function(){var a=m.n(b);a&&a.apply(m.da,arguments)};a.$[b]=c}return c?c:null};var Fg=function(a,b){var c="ytPlayer"+b+a.H;a.A[b]=c;m.da[c]=function(c){var e=m.x(function(){a.fa()||(a.O.publish(b,c),m.ub(a.T,e.toString()))},0);m.vb(a.T,e.toString(),!0)};return c};var Gg=function(a){return(a=Bg(a))?"div"==a.tagName.toLowerCase()?"html5":"flash":null};
var Hg=function(a){m.uc("dcp");a.cancel();tg(a);a.B=null;a.da&&(a.da.loaded=!1);var b=Bg(a);"html5"==Gg(a)?a.ga=b:b&&b.destroy&&b.destroy();m.Sb(a.vf)};m.Ig=function(a,b){a=m.ja(a)?m.Ib(a):a;b=m.Fd(b);var c=Jg+"_"+m.oa(a),d=Kg[c];if(d)return d.lj(b),d.g;d=new sg(a,c);Kg[c]=d;m.A("player-added",d.g);m.Ta(d,m.r(Lg,d));m.x(function(){d.lj(b)},0);return d.g};var Mg=function(){for(var a in Kg){var b=Kg[a];b&&b.cancel()}};m.Ng=function(a){if(a=m.G(a))a=Jg+"_"+m.oa(a),(a=Kg[a])&&a.dispose()};
var Lg=function(a){Kg[a.getId()]=null};m.Og=function(a){a=m.G(a);if(!a)return null;var b=Jg+"_"+m.oa(a),c=Kg[b];c||(c=new sg(a,b),Kg[b]=c);return c.g};
var Pg=function(){m.l("yt.abuse.botguardInitialized",Gd,void 0);m.l("yt.abuse.invokeBotguard",m.Id,void 0);m.l("yt.player.exports.navigate",m.be,void 0);m.l("yt.player.embed",m.Ig,void 0);m.l("yt.player.destroy",m.Ng,void 0);m.l("yt.player.cancelAll",Mg,void 0);m.l("yt.player.getPlayerByElement",m.Og,void 0);m.l("yt.player.exports.feedbackStart",m.zf,void 0);m.l("yt.player.exports.feedbackShowArticle",m.Cf,void 0);m.l("yt.util.activity.init",m.Vd,void 0);m.l("yt.util.activity.getTimeSinceActive",
m.Xd,void 0);m.l("yt.util.activity.setTimestamp",Wd,void 0);var a=m.n("ytplayer.config");Qg(a);m.n("ytspf.enabled")&&(Rg=m.$a(Sg,5E3),(a=m.Tg())?(a.addEventListener("onReady",Sg),a.addEventListener("onStateChange",Sg)):Ug("unable to init PP monitor"))};var Qg=function(a){Mg();if(a=a||null){var b=m.Tg(),c=!0;b&&b.getVideoData&&(c=b.getVideoData(),c=c.video_id!=a.args.video_id||c.list!=a.args.list);c?(Vg="",m.Ig("player-api",a)):b.playVideo();a=m.Fd(a);a.loaded=!0}Sg();m.l("ytplayer.config",a,void 0)};
m.Tg=function(){var a=m.n("yt.player.getPlayerByElement");return a?a("player-api"):null};var Sg=function(){var a=m.G("player"),b=m.Tg();if(a&&b){var a=a&&m.C(a,"off-screen"),c=1==(b&&b.isReady()?b.getPlayerState():void 0),d="watch"==m.v("PAGE_NAME");c&&!d&&(Ug("PP playing off watch (paused)"),b.pauseVideo());a&&d?Ug("PP off-screen on watch"):a||d||Ug("PP !off-screen off watch")}};
var Ug=function(a){var b=m.v("PAGE_NAME");b&&(b=[b,Vg,m.n("_spf_state.nav-counter")],a+="("+b.join(",")+")",m.l("yt.www.persistentplayer.issue",a,void 0),m.cb(Error(a),"WARNING"))};var Wg=function(){m.uc("ol");Xg("init");var a=m.v("PAGE_NAME");a&&Xg("init-"+a);Mc()};var Xg=function(a){m.Nc()?Yg.push(m.Pc(m.r(m.mb,a),0)):m.A(a)};var Zg=function(){m.Sc(Yg);Yg.length=0;var a=m.v("PAGE_NAME");a&&m.mb("dispose-"+a);m.mb("dispose")};var $g=function(){Wg()};
var ah=function(){m.v("TIMING_REPORT_ON_UNLOAD")&&Lc(!0);m.v("EXP_DEFER_CSI_PING")&&Ic("u");Zg()};var bh=function(a,b,c,d,e){for(var f=window.document.getElementsByTagName("script"),h=!1,k=0,p=f.length;k<p;k++)if(0<f[k].src.indexOf("/debug-")){h=!0;break}h&&(e||(e=Error(),e.message=a,e.fileName=b,e.lineNumber=c,(0,window.isNaN)(d)||(e.columnNumber=d)),m.cb(e))};
var ch=function(){dh=1;eh=0;m.v("TIMING_REPORT_ON_UNLOAD")&&Lc(!0);m.v("EXP_DEFER_CSI_PING")&&Ic("n");Fc(void 0);Gc();m.v("CSI_TRACK_ON_BEGIN")&&xc("nb");wc("mark_navigation_requested");fh(gh);m.mb("navigate")};var hh=function(a){a=a.detail.part||a.detail.partial;m.uc("nc"+eh);++eh;var b=1==dh;dh=2;b?(fh(ih),jh()):fh(kh);(a=a.data&&a.data.swfcfg)&&lh(a)};var mh=function(){};var nh=function(a){a=a.detail.response;var b=1==dh;dh=3;b&&(fh(oh),jh());(a=a.data&&a.data.swfcfg)&&lh(a)};
var ph=function(a){m.uc("nd");a=a.detail.response;m.qh=a.cacheKey;a=a.timing;var b=window._spf_state,b=b&&b["nav-counter"]||0;yc(void 0).yt_nav=b;xc("ne",a.responseStart);b=Math.max(0,a.responseStart-a.navigationStart);yc(void 0).srt=b;b=a.spfCached?"hot":"warm";yc(void 0).yt_lt=b;b=+!!a.spfPrefetched;yc(void 0).yt_pft=b;a=a.responseStart-a.fetchStart;Dc(void 0).span.req=a;fh(rh);window.document.getElementById("content").style.height="";Wg();dh=0};
var sh=function(a){var b=a.detail.url;if(a=a.detail.err)a.message&&(a.message+=" (url: "+b+")"),m.cb(a)};var th=function(a){a=m.oc({spfreload:"1",url:a.detail.url,reason:a.detail.reason});m.Ad(a)};var uh=function(){vh()};var wh=function(){};
var jh=function(){window.scroll(0,0);var a=window.document.getElementById("content");-1<a.className.indexOf("spf-animate")&&(a.style.height=a.clientHeight+"px");Zg();for(var b in m.Ya)delete m.Ya[b];m.l("ytplayer.config",null,void 0);if((a=m.Tg())&&a.stopVideo){if(a.stopVideo(),a=a.getLastError())Vg=a,(a=m.G("movie_player"))&&a.stopVideo?(a.stopVideo(),Vg="recovered"):Vg="missing2"}else Vg="missing";Sg()};var lh=function(a){"cfg"in vc(void 0)||m.uc("cfg");Qg(a)};
var fh=function(a){function b(){var b=a[0],e=a[1],f=a[2];c.className="";var h=c.style;h.transitionDuration=h.webkitTransitionDuration=b+"ms";h.width=e+"%";m.ab(xh);xh=m.x(function(){c.className=f},b)}var c=window.document.getElementById("progress");c||(c=window.document.createElement("div"),c.id="progress",c.innerHTML="<dt><dd>",window.document.body.appendChild(c));m.Oc()?(m.Rc(yh),yh=m.Pc(b,0)):(m.ab(xh),xh=m.x(b,0))};
var vh=function(){var a=rh[0]+50;m.ab(xh);xh=m.x(function(){var a=window.document.getElementById("progress");a&&a.parentNode.removeChild(a)},a)};var zh=function(){var a=!1;640>(window.innerWidth||window.document.documentElement.clientWidth)&&(a=!0);m.pb(m.G("player"),"watch-tiny",a);m.pb(window.document.body,"watch-while-skinny",a)};var Ah=function(){m.Tc.call(this,"www/base");this.g=0};var Bh=function(a){(a=a.detail.name)&&Xc(a)};m.ba=[];m.Ch=m.Ch||{};m.da=this;
pa="closure_uid_"+(1E9*Math.random()>>>0);qa=0;m.I=Date.now||function(){return+new Date};Function.prototype.bind=Function.prototype.bind||function(a,b){if(1<arguments.length){var c=Array.prototype.slice.call(arguments,1);c.unshift(this,a);return m.q.apply(null,c)}return(0,m.q)(this,a)};m.ta[" "]=m.ea;m.t(m.ua,Error);m.ua.prototype.name="CustomError";var ya,za,Aa,Ba,Ca,Da,xa;m.Fa=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};ya=/&/g;za=/</g;Aa=/>/g;Ba=/"/g;Ca=/'/g;Da=/\x00/g;xa=/[\x00&<>"']/;m.Dh=2147483648*Math.random()|0;m.Qa=Array.prototype;m.Na=m.Qa.indexOf?function(a,b,c){return m.Qa.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(m.ja(a))return m.ja(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};
m.Eh=m.Qa.lastIndexOf?function(a,b,c){return m.Qa.lastIndexOf.call(a,b,null==c?a.length-1:c)}:function(a,b,c){c=null==c?a.length-1:c;0>c&&(c=Math.max(0,a.length+c));if(m.ja(a))return m.ja(b)&&1==b.length?a.lastIndexOf(b,c):-1;for(;0<=c;c--)if(c in a&&a[c]===b)return c;return-1};m.z=m.Qa.forEach?function(a,b,c){m.Qa.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=m.ja(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};
m.ob=m.Qa.filter?function(a,b,c){return m.Qa.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,h=m.ja(a)?a.split(""):a,k=0;k<d;k++)if(k in h){var p=h[k];b.call(c,p,k,a)&&(e[f++]=p)}return e};m.Fh=m.Qa.map?function(a,b,c){return m.Qa.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=m.ja(a)?a.split(""):a,h=0;h<d;h++)h in f&&(e[h]=b.call(c,f[h],h,a));return e};
m.Gh=m.Qa.reduce?function(a,b,c,d){d&&(b=(0,m.q)(b,d));return m.Qa.reduce.call(a,b,c)}:function(a,b,c,d){var e=c;(0,m.z)(a,function(c,h){e=b.call(d,e,c,h,a)});return e};m.Hh=m.Qa.some?function(a,b,c){return m.Qa.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=m.ja(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1};
m.Ih=m.Qa.every?function(a,b,c){return m.Qa.every.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=m.ja(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&!b.call(c,e[f],f,a))return!1;return!0};m.u.prototype.kb=!1;m.u.prototype.fa=function(){return this.kb};m.u.prototype.dispose=function(){this.kb||(this.kb=!0,this.M())};m.u.prototype.M=function(){if(this.va)for(;this.va.length;)this.va.shift()()};m.t(m.Va,m.u);m.g=m.Va.prototype;m.g.Uo=1;m.g.Ph=0;m.g.subscribe=function(a,b,c){var d=this.Nb[a];d||(d=this.Nb[a]=[]);var e=this.Uo;this.wa[e]=a;this.wa[e+1]=b;this.wa[e+2]=c;this.Uo=e+3;d.push(e);return e};m.g.unsubscribe=function(a,b,c){if(a=this.Nb[a]){var d=this.wa;if(a=m.Ja(a,function(a){return d[a+1]==b&&d[a+2]==c}))return this.Ib(a)}return!1};
m.g.Ib=function(a){if(0!=this.Ph)return this.g||(this.g=[]),this.g.push(a),!1;var b=this.wa[a];if(b){var c=this.Nb[b];c&&m.Oa(c,a);delete this.wa[a];delete this.wa[a+1];delete this.wa[a+2]}return!!b};m.g.publish=function(a,b){var c=this.Nb[a];if(c){this.Ph++;for(var d=Array(arguments.length-1),e=1,f=arguments.length;e<f;e++)d[e-1]=arguments[e];e=0;for(f=c.length;e<f;e++){var h=c[e];this.wa[h+1].apply(this.wa[h+2],d)}this.Ph--;if(this.g&&0==this.Ph)for(;c=this.g.pop();)this.Ib(c);return 0!=e}return!1};
m.g.clear=function(a){if(a){var b=this.Nb[a];b&&((0,m.z)(b,this.Ib,this),delete this.Nb[a])}else this.wa.length=0,this.Nb={}};m.g.ta=m.aa(3);m.g.M=function(){m.Va.K.M.call(this);delete this.wa;delete this.Nb;delete this.g};m.Ya=window.yt&&window.yt.config_||{};m.l("yt.config_",m.Ya,void 0);m.l("yt.tokens_",window.yt&&window.yt.tokens_||{},void 0);m.eb=window.yt&&window.yt.msgs_||{};m.l("yt.msgs_",m.eb,void 0);m.Ie="Microsoft Internet Explorer"==window.navigator.appName;var Jh=m.n("yt.pubsub.instance_")||new m.Va;m.Va.prototype.subscribe=m.Va.prototype.subscribe;m.Va.prototype.unsubscribeByKey=m.Va.prototype.Ib;m.Va.prototype.publish=m.Va.prototype.publish;m.Va.prototype.clear=m.Va.prototype.clear;m.l("yt.pubsub.instance_",Jh,void 0);var ib=m.n("yt.pubsub.subscribedKeys_")||{};m.l("yt.pubsub.subscribedKeys_",ib,void 0);var kb=m.n("yt.pubsub.topicToKeys_")||{};m.l("yt.pubsub.topicToKeys_",kb,void 0);var jb=m.n("yt.pubsub.isSynchronous_")||{};
m.l("yt.pubsub.isSynchronous_",jb,void 0);m.hb=m.n("yt.pubsub.skipSubId_")||null;m.l("yt.pubsub.skipSubId_",m.hb,void 0);var yb="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");t:{var Kh=m.da.navigator;if(Kh){var Lh=Kh.userAgent;if(Lh){m.Bb=Lh;break t}}m.Bb=""};var Nh,Fb,Eb,Sh;m.Se=Ab("Opera")||Ab("OPR");m.F=Ab("Trident")||Ab("MSIE");m.Re=Ab("Gecko")&&-1==m.Bb.toLowerCase().indexOf("webkit")&&!(Ab("Trident")||Ab("MSIE"));m.Qe=-1!=m.Bb.toLowerCase().indexOf("webkit");m.Qe&&Ab("Mobile");m.Oe=Ab("Macintosh");m.Ne=Ab("Windows");m.Mh=Ab("Linux")||Ab("CrOS");Nh=m.da.navigator||null;m.Oh=!!Nh&&-1!=(Nh.appVersion||"").indexOf("X11");m.Ph=Ab("Android");m.Qh=Ab("iPhone")&&!Ab("iPod")&&!Ab("iPad");m.Rh=Ab("iPad");
Fb=function(){var a="",b;if(m.Se&&m.da.opera)return a=m.da.opera.version,m.la(a)?a():a;m.Re?b=/rv\:([^\);]+)(\)|;)/:m.F?b=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/:m.Qe&&(b=/WebKit\/(\S+)/);b&&(a=(a=b.exec(m.Bb))?a[1]:"");return m.F&&(b=Cb(),b>(0,window.parseFloat)(a))?String(b):a}();Eb={};Sh=m.da.document;m.Hb=Sh&&m.F?Cb()||("CSS1Compat"==Sh.compatMode?(0,window.parseInt)(Fb,10):5):void 0;var Pb;Pb=!m.F||m.Gb(9);m.Th=!m.Re&&!m.F||m.F&&m.Gb(9)||m.Re&&m.Db("1.9.1");m.Uh=m.F&&!m.Db("9");m.Vh=m.F||m.Se||m.Qe;m.Wh=m.F&&!m.Gb(9);var Mb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};m.Xh=m.Yb(!1);m.Yh=m.Yb(!0);m.bc="StopIteration"in m.da?m.da.StopIteration:Error("StopIteration");m.$b.prototype.next=function(){throw m.bc;};m.$b.prototype.fb=function(){return this};var ic=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/,gc=m.Qe;var vg=/^https?:\/\/([A-Za-z0-9-]{1,63}\.)*(corp\.google\.com|borg\.google\.com|prod\.google\.com|video\.google\.com|youtube\.com|youtube\.googleapis\.com|youtube-nocookie\.com|youtubeeducation\.com)(:[0-9]+)?\/+embed\/+/;var tc={},sc=0,Zh=m.n("yt.net.ping.workerUrl_")||null;m.l("yt.net.ping.workerUrl_",Zh,void 0);var Hc,Jc,Kc;var Ac=window.performance||window.mozPerformance||window.msPerformance||window.webkitPerformance||{},Gc=(0,m.q)(Ac.clearResourceTimings||Ac.webkitClearResourceTimings||Ac.mozClearResourceTimings||Ac.msClearResourceTimings||Ac.oClearResourceTimings||m.ea,Ac),wc=Ac.mark?function(a){Ac.mark(a)}:m.ea;m.g=m.Tc.prototype;m.g.ix=function(){2==this.j||this.init()};m.g.enable=function(){this.j=1;(0,m.z)("string"==typeof this.page?[this.page]:this.page,function(a){a&&(this.subscribe("init-"+a,this.ix,this),this.subscribe("dispose-"+a,this.dispose,this),m.v("PAGE_NAME")==a&&m.Uc(this))},this)};m.g.init=function(){m.Oc()&&m.Rc(this.k);this.j=2;this.B&&this.B()};m.g.dispose=function(){this.j=3;m.Rc(this.k);this.A&&this.A()};m.g.disable=function(){this.j=4;this.clear();this.dispose()};
m.g.subscribe=function(a,b,c){a=m.y(a,b,c);this.wa.push(a);return a};m.g.clear=function(){m.lb(this.wa);this.wa=[]};var Wc=m.n("yt.modules.registry_")||{};m.l("yt.modules.registry_",Wc,void 0);m.$h=null;"undefined"!=typeof window.XMLHttpRequest?m.$h=function(){return new window.XMLHttpRequest}:"undefined"!=typeof window.ActiveXObject&&(m.$h=function(){return new window.ActiveXObject("Microsoft.XMLHTTP")});var $c,ad,bd,cd,jd,md=0,kd=0,id=[],hd=/.+\.googlevideo\.com|c\.youtube\.com|\/videoplayback\?|spf\=navigate/g;var pd={};var ud=/\.vflset|-vfl[a-zA-Z0-9_+=-]+/,vd=/-[a-zA-Z]{2,3}_[a-zA-Z]{2,3}(?=(\/|$))/;m.zd=m.hc;var Cd={enablejsapi:1},Dd={},Ed={allowscriptaccess:"always",allowfullscreen:"true",bgcolor:"#000000"};Bd.prototype.clone=function(){var a=new Bd,b;for(b in this){var c=this[b];"object"==m.ga(c)?a[b]=m.wb(c):a[b]=c}return a};m.Hd=null;m.ai=m.Qe?"webkit":m.Re?"moz":m.F?"ms":m.Se?"o":"";m.bi=m.n("yt.dom.getNextId_");if(!m.bi){m.bi=function(){return++ci};m.l("yt.dom.getNextId_",m.bi,void 0);var ci=0};m.g=m.Kd.prototype;m.g.ua=null;m.g.type="";m.g.target=null;m.g.relatedTarget=null;m.g.currentTarget=null;m.g.data=null;m.g.source=null;m.g.state=null;m.g.keyCode=0;m.g.charCode=0;m.g.altKey=!1;m.g.ctrlKey=!1;m.g.shiftKey=!1;m.g.clientX=0;m.g.clientY=0;m.g.wheelDeltaX=0;m.g.wheelDeltaY=0;m.g.rotation=0;m.g.scale=1;m.g.changedTouches=null;m.g.preventDefault=m.aa(4);m.g.stopPropagation=m.aa(5);m.g.stopImmediatePropagation=m.aa(6);
var Ld={stopImmediatePropagation:1,stopPropagation:1,preventMouseEvent:1,preventManipulation:1,preventDefault:1,layerX:1,layerY:1,scale:1,rotation:1};m.Nd=m.n("yt.events.listeners_")||{};m.l("yt.events.listeners_",m.Nd,void 0);var Od=m.n("yt.events.counter_")||{count:0};m.l("yt.events.counter_",Od,void 0);m.Rd=/\s*;\s*/;m.g=m.Pd.prototype;m.g.isEnabled=m.aa(7);m.g.set=function(a,b,c,d,e,f){if(/[;=\s]/.test(a))throw Error('Invalid cookie name "'+a+'"');if(/[;\r\n]/.test(b))throw Error('Invalid cookie value "'+b+'"');m.ca(c)||(c=-1);e=e?";domain="+e:"";d=d?";path="+d:"";f=f?";secure":"";c=0>c?"":0==c?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date((0,m.I)()+1E3*c)).toUTCString();this.g.cookie=a+"="+b+e+d+c+f};
m.g.get=function(a,b){for(var c=a+"=",d=(this.g.cookie||"").split(m.Rd),e=0,f;f=d[e];e++){if(0==f.lastIndexOf(c,0))return f.substr(c.length);if(f==a)return""}return b};m.g.remove=function(a,b,c){var d=m.ca(this.get(a));this.set(a,"",0,b,c);return d};m.g.Sa=m.aa(8);m.g.xa=m.aa(9);m.g.isEmpty=m.aa(10);m.g.ta=m.aa(2);m.g.uf=m.aa(11);m.g.clear=function(){for(var a=m.Qd(this).keys,b=a.length-1;0<=b;b--)this.remove(a[b])};m.Td=new m.Pd(window.document);m.Td.j=3950;var le;var fe,he=!1,ie=[];m.oe.prototype.then=function(a,b,c){return m.ve(this,m.la(a)?a:null,m.la(b)?b:null,c)};m.me(m.oe);m.oe.prototype.cancel=function(a){0==this.j&&ee(function(){var b=new we(a);re(this,b)},this)};m.oe.prototype.G=function(a){this.j=0;pe(this,2,a)};m.oe.prototype.J=function(a){this.j=0;pe(this,3,a)};m.oe.prototype.H=function(){for(;this.g&&this.g.length;){var a=this.g;this.g=[];for(var b=0;b<a.length;b++)se(this,a[b],this.j,this.C)}this.B=!1};var ze=ce;m.t(we,m.ua);we.prototype.name="cancel";var De=null;Ae.prototype.A=function(a){Ee(this,"startFeedback",arguments)};Ae.prototype.B=function(a){Ee(this,"startHelp",arguments)};Ae.prototype.g=function(a){Ee(this,"loadChatSupport",arguments)};var di=!1,ei="";
if(window.navigator.plugins&&window.navigator.plugins.length){var fi=window.navigator.plugins["Shockwave Flash"];fi&&(di=!0,fi.description&&(ei=Fe(fi.description)));window.navigator.plugins["Shockwave Flash 2.0"]&&(di=!0,ei="2.0.0.11")}else if(window.navigator.mimeTypes&&window.navigator.mimeTypes.length){var gi=window.navigator.mimeTypes["application/x-shockwave-flash"];(di=gi&&gi.enabledPlugin)&&(ei=Fe(gi.enabledPlugin.description))}else try{var hi=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash.7"),di=
!0,ei=Fe(hi.GetVariable("$version"))}catch(aaa){try{hi=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash.6"),di=!0,ei="6.0.21"}catch(baa){try{hi=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash"),di=!0,ei=Fe(hi.GetVariable("$version"))}catch(caa){}}}m.ii=di;m.ji=ei;var ki,li,mi,ni,oi,pi,qi,ti,wi;qi=pi=oi=ni=mi=li=ki=!1;var ri=m.Bb;ri&&(-1!=ri.indexOf("Firefox")?ki=!0:-1!=ri.indexOf("Camino")?li=!0:-1!=ri.indexOf("iPad")?ni=!0:-1!=ri.indexOf("iPhone")||-1!=ri.indexOf("iPod")?mi=!0:-1!=ri.indexOf("Chrome")?pi=!0:-1!=ri.indexOf("Android")?oi=!0:-1!=ri.indexOf("Safari")&&(qi=!0));m.si=ki;ti=li;m.ui=mi;m.vi=ni;wi=oi;m.xi=pi;m.yi=qi;m.zi=function(){if(m.si)return Ge(/Firefox\/([0-9.]+)/);if(m.F||m.Se)return Fb;if(m.xi)return Ge(/Chrome\/([0-9.]+)/);if(m.yi)return Ge(/Version\/([0-9.]+)/);if(m.ui||m.vi){var a;if(a=/Version\/(\S+).*Mobile\/(\S+)/.exec(m.Bb))return a[1]+"."+a[2]}else{if(wi)return(a=Ge(/Android\s+([0-9.]+)/))?a:Ge(/Version\/([0-9.]+)/);if(ti)return Ge(/Camino\/([0-9.]+)/)}return""}();m.fa(He);He.prototype.getVersion=function(){return[this.g,this.j,this.k]};m.g=m.Ue.prototype;m.g.clone=function(){return new m.Ue(this.top,this.right,this.bottom,this.left)};m.g.contains=function(a){return m.Ve(this,a)};m.g.ceil=m.aa(12);m.g.floor=function(){this.top=Math.floor(this.top);this.right=Math.floor(this.right);this.bottom=Math.floor(this.bottom);this.left=Math.floor(this.left);return this};m.g.round=function(){this.top=Math.round(this.top);this.right=Math.round(this.right);this.bottom=Math.round(this.bottom);this.left=Math.round(this.left);return this};
m.g.scale=function(a,b){var c=m.ka(b)?b:a;this.left*=a;this.right*=a;this.top*=c;this.bottom*=c;return this};var sf=m.zb("area base br col command embed hr img input keygen link meta param source track wbr".split(" "));m.Ai=RegExp("^[^\u0591-\u07ff\u200f\ufb1d-\ufdff\ufe70-\ufefc]*[A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]");m.Bi=RegExp("^[^A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]*[\u0591-\u07ff\u200f\ufb1d-\ufdff\ufe70-\ufefc]");m.Ze.prototype.af=!0;m.Ze.prototype.$e=function(){return this.g};m.Ze.prototype.toString=function(){return"Const{"+this.g+"}"};var $e={};bf.prototype.af=!0;var cf={};bf.prototype.$e=function(){return this.g};var qf=df(""),pf=/^[-.%_!# a-zA-Z0-9]+$/;ef.prototype.af=!0;ef.prototype.$e=function(){return""};ef.prototype.Dk=!0;ef.prototype.ag=function(){return 1};var ff={};gf.prototype.af=!0;gf.prototype.$e=function(){return""};gf.prototype.Dk=!0;gf.prototype.ag=function(){return 1};var hf={};var nf,rf,of,kf;jf.prototype.Dk=!0;jf.prototype.ag=function(){return this.j};jf.prototype.af=!0;jf.prototype.$e=function(){return this.g};nf=/^[a-zA-Z0-9-]+$/;rf=m.zb("action","cite","data","formaction","href","manifest","poster","src");of=m.zb("embed","iframe","link","script","style","template");kf={};m.Ci=uf("",0);m.Di=m.Zb(function(){if(m.F)return m.Db("10.0");var a=window.document.createElement("div"),b=m.Te(),c={transition:"opacity 1s linear"};b&&(c[b+"-transition"]="opacity 1s linear");b=m.mf("div",{style:c});a.innerHTML=m.lf(b);a=a.firstChild;b=a.style[m.Ha("transition")];return""!=("undefined"!==typeof b?b:a.style[m.We(a,"transition")]||"")});var Bf;m.xf={};Bf=!1;m.fa(m.Df);m.Ef=m.n("yt.prefs.UserPrefs.prefs_")||{};m.l("yt.prefs.UserPrefs.prefs_",m.Ef,void 0);m.g=m.Df.prototype;m.g.get=function(a,b){Gf(a);Ff(a);var c=void 0!==m.Ef[a]?m.Ef[a].toString():null;return null!=c?c:b?b:""};m.g.set=function(a,b){Gf(a);Ff(a);if(null==b)throw"ExpectedNotNull";m.Ef[a]=b.toString()};m.g.remove=function(a){Gf(a);Ff(a);delete m.Ef[a]};m.g.save=function(){var a;a=[];for(var b in m.Ef)a.push(b+"="+(0,window.escape)(m.Ef[b]));a=a.join("&");m.Sd("PREF",a,63072E3)};
m.g.clear=function(){m.Ef={}};var Rf=/cssbin\/(?:debug-)?([a-zA-Z0-9_-]+?)(?:-2x|-web|-rtl|-vfl|.css)/;var Tf;var Ei=m.Bb,Ei=Ei.toLowerCase();if(-1!=Ei.indexOf("android")){var Fi=Ei.match(/android\D*(\d\.\d)[^\;|\)]*[\;\)]/);if(Fi)Tf=Number(Fi[1]);else{var Gi={cupcake:1.5,donut:1.6,eclair:2,froyo:2.2,gingerbread:2.3,honeycomb:3,"ice cream sandwich":4,jellybean:4.1},Hi=Ei.match("("+m.sb(Gi).join("|")+")");Tf=Hi?Gi[Hi[0]]:0}}else Tf=void 0;m.t(m.Vf,Uf);m.Vf.prototype.ta=m.aa(1);m.Vf.prototype.clear=function(){var a=m.dc(this.fb(!0)),b=this;(0,m.z)(a,function(a){b.remove(a)})};m.t(m.Wf,m.Vf);m.g=m.Wf.prototype;m.g.isAvailable=function(){if(!this.g)return!1;try{return this.g.setItem("__sak","1"),this.g.removeItem("__sak"),!0}catch(a){return!1}};m.g.set=function(a,b){try{this.g.setItem(a,b)}catch(c){if(0==this.g.length)throw"Storage mechanism: Storage disabled";throw"Storage mechanism: Quota exceeded";}};m.g.get=function(a){a=this.g.getItem(a);if(!m.ja(a)&&null!==a)throw"Storage mechanism: Invalid value was encountered";return a};m.g.remove=function(a){this.g.removeItem(a)};
m.g.ta=m.aa(0);m.g.fb=function(a){var b=0,c=this.g,d=new m.$b;d.next=function(){if(b>=c.length)throw m.bc;var d;d=c.key(b++);if(a)return d;d=c.getItem(d);if(!m.ja(d))throw"Storage mechanism: Invalid value was encountered";return d};return d};m.g.clear=function(){this.g.clear()};m.g.key=function(a){return this.g.key(a)};m.t(m.Xf,m.Wf);m.t(Yf,m.Wf);var fg={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},eg=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;m.gg.prototype.set=function(a,b){m.ca(b)?this.g.set(a,m.$f(b)):this.g.remove(a)};m.gg.prototype.get=function(a){var b;try{b=this.g.get(a)}catch(c){return}if(null!==b)try{return m.Zf(b)}catch(d){throw"Storage: Invalid value was encountered";}};m.gg.prototype.remove=function(a){this.g.remove(a)};m.t(hg,m.gg);hg.prototype.set=function(a,b){hg.K.set.call(this,a,jg(b))};hg.prototype.j=function(a){a=hg.K.get.call(this,a);if(!m.ca(a)||a instanceof Object)return a;throw"Storage: Invalid value was encountered";};hg.prototype.get=function(a){if(a=this.j(a)){if(a=a.data,!m.ca(a))throw"Storage: Invalid value was encountered";}else a=void 0;return a};m.t(kg,hg);kg.prototype.set=function(a,b,c){if(b=jg(b)){if(c){if(c<(0,m.I)()){kg.prototype.remove.call(this,a);return}b.expiration=c}b.creation=(0,m.I)()}kg.K.set.call(this,a,b)};kg.prototype.j=function(a,b){var c=kg.K.j.call(this,a);if(c)if(!b&&m.lg(c))kg.prototype.remove.call(this,a);else return c};m.t(m.mg,kg);var Ii,Ji;Ii=new m.Xf;m.og=Ii.isAvailable()?new m.mg(Ii):null;Ji=new Yf;m.pg=Ji.isAvailable()?new m.mg(Ji):null;m.t(sg,m.u);m.g=sg.prototype;m.g.getId=function(){return this.H};m.g.lj=function(a,b){this.fa()||(ug(this,a),Cg(this,b),this.C&&yg(this))};m.g.wt=function(){return this.Aa};
m.g.Gy=function(){if(!this.N){var a=Dg(this);a&&"html5"==Gg(this)?(this.B="html5",this.C||this.Ke()):(Hg(this),this.B="html5",a&&this.ga?(this.vf.appendChild(this.ga),this.Ke()):(this.da.loaded=!0,this.G=(0,m.q)(function(){var a=this.vf,c=this.da.clone();m.n("yt.player.Application.create")(a,c);this.Ke()},this),this.N=!0,a?this.G():(m.qd(this.da.assets.js,this.G),m.Qf(this.da.assets.css))))}};
m.g.Fy=function(){var a=this.da.clone();a.attrs.width=a.attrs.width||"100%";a.attrs.height=a.attrs.height||"100%";"flash"==Gg(this)?(this.B="flash",this.C||Of(a,!1,(0,m.q)(this.Ke,this))):(Hg(this),this.B="flash",this.da.loaded=!0,m.Kf(this.vf,a),this.Ke())};
m.g.Ke=function(){var a=Bg(this),b=!1;try{a&&a.getApiInterface&&a.getApiInterface()&&(b=!0)}catch(c){}if(b)if(this.N=!1,a.isNotServable&&a.isNotServable())Ag(this);else{tg(this);this.C=!0;a=Bg(this);a.addEventListener&&(this.J=Eg(this,a,"addEventListener"));a.removeEventListener&&(this.U=Eg(this,a,"removeEventListener"));for(var b=a.getApiInterface(),b=b.concat(a.getInternalApiInterface()),d=0;d<b.length;d++){var e=b[d];this.g[e]||(this.g[e]=Eg(this,a,e))}for(var f in this.A)this.J(f,this.A[f]);yg(this);
this.X&&this.X(this.g);this.O.publish("onReady",this.g)}else this.za=m.x((0,m.q)(this.Ke,this),50)};m.g.Bt=function(){return this.C};m.g.ue=function(a,b){if(!this.fa()){var c=wg(this,b);if(c){if(!m.Ma(this.Fa,a)&&!this.A[a]){var d=Fg(this,a);this.J&&this.J(a,d)}this.O.subscribe(a,c);"onReady"==a&&this.C&&m.x(m.r(c,this.g),0)}}};m.g.At=function(a,b){if(!this.fa()){var c=wg(this,b);c&&this.O.unsubscribe(a,c)}};
m.g.Qp=function(a){a=a?Ub:Tb;for(var b=a(window.document.activeElement);b&&(1!=b.nodeType||(b.focus(),b!=window.document.activeElement));)b=a(b)};m.g.Sp=function(a){var b={};b.volume=(0,window.isNaN)(a.volume)?rg().volume:m.qb(a.volume,0,100);b.muted=void 0==a.muted?rg().muted:a.muted;m.ng("yt-player-volume",b,2592E3)};m.g.Rp=function(a){5==a&&Ag(this)};m.g.Tp=function(a){m.A("WATCH_LATER_VIDEO_ADDED",a)};m.g.Vp=function(a){m.A("WATCH_LATER_VIDEO_REMOVED",a)};
m.g.Hy=function(){Hg(this);this.B="unsupported";var a='Adobe Flash Player or an HTML5 supported browser is required for video playback. <br> <a href="http://get.adobe.com/flashplayer/">Get the latest Flash Player</a> <br> <a href="/html5">Learn more about upgrading to an HTML5 browser</a>',b=window.navigator.userAgent.match(/Version\/(\d).*Safari/);b&&5<=(0,window.parseInt)(b[1],10)&&(a='Adobe Flash Player or QuickTime is required for video playback. <br> <a href="http://get.adobe.com/flashplayer/"> Get the latest Flash Player</a> <br> <a href="http://www.apple.com/quicktime/download/">Get the latest version of QuickTime</a>');
b=this.da.messages.player_fallback||a;a=m.G("player-unavailable");m.G("unavailable-submessage")&&a&&(m.G("unavailable-submessage").innerHTML=b,(b=m.H("icon",a))&&m.od(b,"icon")&&(b.src=m.J(b,"icon")),m.E(a,"hid"),m.D(m.G("player"),"off-screen-trigger"))};m.g.zt=function(){return this.B||Gg(this)};m.g.xt=function(){return this.oa};m.g.cancel=function(){this.G&&m.sd(this.da.assets.js,this.G);m.ab(this.za);this.N=!1};
m.g.M=function(){Hg(this);this.$=null;for(var a in this.A)m.da[this.A[a]]=null;this.g=null;delete this.vf;delete this.k;this.da&&(this.Aa=this.da=this.da.fallback=null);sg.K.M.call(this)};var Kg={},Jg="player_uid_"+(1E9*Math.random()>>>0);var Ki=m.n("yt.abuse.botguardInitialized")||Gd;m.l("yt.abuse.botguardInitialized",Ki,void 0);var Li=m.n("yt.abuse.invokeBotguard")||m.Id;m.l("yt.abuse.invokeBotguard",Li,void 0);var Mi=m.n("yt.player.exports.navigate")||m.be;m.l("yt.player.exports.navigate",Mi,void 0);var Ni=m.n("yt.player.embed")||m.Ig;m.l("yt.player.embed",Ni,void 0);var Oi=m.n("yt.player.destroy")||m.Ng;m.l("yt.player.destroy",Oi,void 0);var Pi=m.n("yt.player.cancelAll")||Mg;m.l("yt.player.cancelAll",Pi,void 0);
var Qi=m.n("yt.player.getPlayerByElement")||m.Og;m.l("yt.player.getPlayerByElement",Qi,void 0);var Ri=m.n("yt.player.exports.feedbackStart")||m.zf;m.l("yt.player.exports.feedbackStart",Ri,void 0);var Si=m.n("yt.player.exports.feedbackShowArticle")||m.Cf;m.l("yt.player.exports.feedbackShowArticle",Si,void 0);var Ti=m.n("yt.util.activity.init")||m.Vd;m.l("yt.util.activity.init",Ti,void 0);var Ui=m.n("yt.util.activity.getTimeSinceActive")||m.Xd;m.l("yt.util.activity.getTimeSinceActive",Ui,void 0);
var Vi=m.n("yt.util.activity.setTimestamp")||Wd;m.l("yt.util.activity.setTimestamp",Vi,void 0);var Rg,Vg="";var Yg=[];var dh,xh,yh,eh,gh,oh,ih,kh,rh;eh=0;gh=[900,60,"waiting"];oh=[500,99,"waiting"];ih=[300,60,"waiting"];kh=[400,99,"waiting"];rh=[300,101,"done"];var Wi=[];window.yt=window.yt||{};m.l("yt.setConfig",m.Wa,void 0);m.l("yt.getConfig",m.v,void 0);m.l("yt.hasMsg",m.db,void 0);m.l("yt.pubsub.publish",m.A,void 0);m.l("yt.pubsub.subscribe",m.y,void 0);m.l("yt.setMsg",function(a){Xa(m.eb,arguments)},void 0);m.l("yt.setGoogMsg",function(a){Xa(m.eb,arguments)},void 0);m.l("yt.setAjaxToken",function(){},void 0);
m.l("reportTimingMaps",function(a,b,c,d){if(a)for(var e in a)m.uc(e,a[e],d);if(c)for(var f in c)if("number"==typeof c[f])a=f,e=c[f],Dc(d).span[a]=e;else{a=f;e=c[f];var h=d,k=Dc(h).span,h=vc(h);e in h&&(k[a]=(0,m.I)()-h[e])}if(b)for(var p in b)c=p,f=b[p],yc(d)[c]=f;return Mc(d)},void 0);
m.l("yt.timing.reportAdToVideo",function(a,b,c){c={v:2,s:"youtube",action:c?"watch,ad2video_html5":"watch,ad2video"};a.aft=a.pbs=a.astv||a.actv;var d=[],e;for(e in a)"_"!=e.charAt(0)&&d.push(e+"."+a[e]);c.rt=d.join(",");for(var f in b)"_"!=f.charAt(0)&&(c[f]=b[f]);a=m.v("TIMING_INFO")||{};"e"in a&&(c.e=a.e);"ei"in a&&(c.ei=a.ei);Ec(c)},void 0);m.t(Ah,m.Tc);
Ah.prototype.enable=function(){window.onload=$g;window.onunload=ah;window.onerror=bh;var a=window.ytspf||{};a.enabled?(window.addEventListener&&(window.addEventListener("spfrequest",ch),window.addEventListener("spfpartprocess",hh),window.addEventListener("spfpartdone",mh),window.addEventListener("spfprocess",nh),window.addEventListener("spfdone",ph),window.addEventListener("spferror",sh),window.addEventListener("spfreload",th),window.addEventListener("spfjsbeforeunload",Bh)),a.config=a.config||{},
window.ytdepmap?window.spf.script.ready("spf",function(){a.enabled=window.spf.init(a.config)}):a.enabled=window.spf.init(a.config),this.subscribe("init",uh),this.subscribe("dispose",wh)):window.spf.dispose();this.subscribe("init",this.init,this);this.subscribe("dispose",this.dispose,this)};
Ah.prototype.init=function(){Ah.K.init.call(this);(window.ytspf||{}).enabled||window.spf.dispose();Zc();var a=window.ytPageFrameLoaded||!1,b,c;!a&&m.v("PAGEFRAME_JS")?(b=m.v("PAGEFRAME_JS"),c=function(){m.n("ytbin.www.pageframe.setup")();window.ytPageFrameLoaded=!0}):a&&(a=m.n("yt.www.masthead.loadSearchbox"))&&a();var a=m.v("JS_COMMON_MODULE"),d=m.v("JS_PAGE_MODULES");if(window.ytdepmap)d||(d=[a]),a=m.v("JS_DELAY_LOAD",void 0),0<a?(m.ab(this.g),this.g=m.x(function(){b&&m.qd(b,c);window.spf.script.require(d)},
a)):(b&&m.qd(b,c),window.spf.script.require(d));else{var e={};e[a]=d;a=m.v("JS_DELAY_LOAD",void 0);0<a?(m.ab(this.g),this.g=m.x(function(){b&&m.qd(b,c);m.td(e)},a)):(b&&m.qd(b,c),m.td(e))}m.v("SKYWATCH_ENABLED")&&(Wi.push(m.y("page-resize",zh)),zh());Pg();var a=!!m.n("yt.reactLoaded"),f=m.v("REACT_JS");!a&&f&&m.qd(f,function(){m.l("yt.reactLoaded",!0,void 0)})};
Ah.prototype.dispose=function(){m.ab(this.g);var a=m.n("ytbin.www.pageframe.cancelSetup");a&&a();m.lb(Wi);Wi.length=0;m.bb(Rg);if(a=m.Tg())a.removeEventListener("onReady",Sg),a.removeEventListener("onStateChange",Sg);Ah.K.dispose.call(this)};
Ah.prototype.disable=function(){Ah.K.disable.call(this);window.removeEventListener&&(window.removeEventListener("spfrequest",ch),window.removeEventListener("spfpartprocess",hh),window.removeEventListener("spfpartdone",mh),window.removeEventListener("spfprocess",nh),window.removeEventListener("spfdone",ph),window.removeEventListener("spferror",sh),window.removeEventListener("spfreload",th),window.removeEventListener("spfjsbeforeunload",Bh));window.onload=null;window.onunload=null;window.onerror=null};
m.Vc(new Ah);})(_yt_www);
